${XL_IDP_PATH_REFERENCE_SCRIPTS}/bash_dir/reference_container_type.sh
${XL_IDP_PATH_REFERENCE_SCRIPTS}/bash_dir/reference_import_tracking.sh
${XL_IDP_PATH_REFERENCE_SCRIPTS}/bash_dir/reference_lines.sh
${XL_IDP_PATH_REFERENCE_SCRIPTS}/bash_dir/reference_morservice.sh
${XL_IDP_PATH_REFERENCE_SCRIPTS}/bash_dir/reference_region.sh
${XL_IDP_PATH_REFERENCE_SCRIPTS}/bash_dir/reference_statistics.sh
${XL_IDP_PATH_REFERENCE_SCRIPTS}/bash_dir/reference_ship.sh
${XL_IDP_PATH_REFERENCE_SCRIPTS}/bash_dir/reference_is_empty.sh
${XL_IDP_PATH_REFERENCE_SCRIPTS}/bash_dir/reference_inn.sh
${XL_IDP_PATH_REFERENCE_SCRIPTS}/bash_dir/reference_tnved2.sh
#${XL_IDP_PATH_REFERENCE_SCRIPTS}/bash_dir/reference_inn_by_api.sh